// 各种请求状态

// 获取员工等待接单信息
export const GET_MEMBER_WAITING_ORDERS = 'GET_MEMBER_WAITING_ORDERS';
export const GET_MEMBER_WAITING_ORDERS_REQUEST = 'GET_MEMBER_WAITING_ORDERS_REQUEST';
export const GET_MEMBER_WAITING_ORDERS_SUCCESS = 'GET_MEMBER_WAITING_ORDERS_SUCCESS';
export const GET_MEMBER_WAITING_ORDERS_FAILURE = 'GET_MEMBER_WAITING_ORDERS_FAILURE';
export const GET_MEMBER_WAITING_ORDERS_FILTER_SUCCESS = 'GET_MEMBER_WAITING_ORDERS_FILTER_SUCCESS';


// 获取员工已接派单信息
export const GET_MEMBER_RECEIVING_ORDERS = 'GET_MEMBER_RECEIVING_ORDERS';
export const GET_MEMBER_RECEIVING_ORDERS_REQUEST = 'GET_MEMBER_RECEIVING_ORDERS_REQUEST';
export const GET_MEMBER_RECEIVING_ORDERS_SUCCESS = 'GET_MEMBER_RECEIVING_ORDERS_SUCCESS';
export const GET_MEMBER_RECEIVING_ORDERS_FAILURE = 'GET_MEMBER_RECEIVING_ORDERS_FAILURE';
export const GET_MEMBER_RECEIVING_ORDERS_FILTER_SUCCESS = 'GET_MEMBER_RECEIVING_ORDERS_FILTER_SUCCESS';

//获取员工所有派单信息
export const GET_MEMBER_ALL_ORDERS = 'GET_MEMBER_RECEIVING_ORDERS';
export const GET_MEMBER_ALL_ORDERS_REQUEST = 'GET_MEMBER_ALL_ORDERS_REQUEST';
export const GET_MEMBER_ALL_ORDERS_SUCCESS = 'GET_MEMBER_ALL_ORDERS_SUCCESS';
export const GET_MEMBER_ALL_ORDERS_FAILURE = 'GET_MEMBER_ALL_ORDERS_FAILURE';

//获取流转其它员工
export const GET_PERSON = 'GET_PERSON';
export const GET_PERSON_REQUEST = 'GET_PERSON_REQUEST';
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS';
export const GET_PERSON_FAILURE = 'GET_PERSON_FAILURE';

//用户端主页
export const GET_ITEM_LIST_REQUEST = 'GET_ITEM_LIST_REQUEST';
export const GET_ITEM_LIST_SUCCESS = 'GET_ITEM_LIST_SUCCESS';
export const GET_ITEM_LIST_FAILURE = 'GET_ITEM_LIST_FAILURE';
export const DO_ITEM_LIST_PLUS = ' DO_ITEM_LIST_PLUS';
export const DO_ITEM_LIST_MINUS = ' DO_ITEM_LIST_MINUS';

//管理端获取订单信息
export const GET_MANAGER_ORDER = 'GET_MANAGER_ORDER';
export const GET_MANAGER_ORDER_REQUEST = 'GET_ITEM_LIST_REQUEST';
export const GET_MANAGER_ORDER_SUCCESS = 'GET_ITEM_LIST_SUCCESS';
export const GET_MANAGER_ORDER_FAILURE = 'GET_ITEM_LIST_FAILURE';


//管理端获取员工列表
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST';
export const GET_EMPLOYEE_LIST_REQUEST = 'GET_EMPLOYEE_LIST_REQUEST';
export const GET_EMPLOYEE_LIST_SUCCESS = 'GET_EMPLOYEE_LIST_SUCCESS';
export const GET_EMPLOYEE_LIST_FAILURE = 'GET_EMPLOYEE_LIST_FAILURE';
export const GET_EMPLOYEE_LIST_ONLINE_SUCCESS = "GET_EMPLOYEE_LIST_ONLINE_SUCCESS";


//获取员工的内容
export const GET_EMPLOYEEDESC = 'GET_EMPLOYEEDESC';
export const GET_EMPLOYEEDESC_REQUEST = 'GET_EMPLOYEEDESC_REQUEST';
export const GET_EMPLOYEEDESC_SUCCESS = 'GET_EMPLOYEEDESC_SUCCESS';
export const GET_EMPLOYEEDESC_FAILURE = 'GET_EMPLOYEEDESC_FAILURE';


//员工所在酒店信息
export const GET_EMPLOYEEHOTELDESC = 'GET_EMPLOYEEHOTELDESC';
export const GET_EMPLOYEEHOTELDESC_REQUEST = 'GET_EMPLOYEEHOTELDESC_REQUEST';
export const GET_EMPLOYEEHOTELDESC_SUCCESS = 'GET_EMPLOYEEHOTELDESC_SUCCESS';
export const GET_EMPLOYEEHOTELDESC_FAILURE = 'GET_EMPLOYEEHOTELDESC_FAILURE';


export const SET_ACTIVE_OPTION = 'SET_ACTIVE_OPTION';